### PR TITLE
Resubmission

### PR DESCRIPTION
**Pull request by JennyVoPhamhi**
Just a pull request to merge the resubmission branch, which contains all the updated figures and figure notebooks for resubmission to PLOS Computational Biology, to master.

### CODE REVIEW

**Review by kevinyamauchi — COMMENTED** [review]
Hey, @JennyVoPhamhi ! Thanks for this. Since there are so many files changed, it was a bit difficult to see exactly what was changed. Can you point me to the files I should review?

Also, would you mind adding .DS_Store to the `.gitignore` so they aren't stored in the repo? Those are just system files that aren't necessary for the repo.

**Comment by JennyVoPhamhi** [comment]
Hey, @kevinyamauchi!

Yes, definitely!

I rm'd all .DS_Store and added **/.DS_Store to the .gitignore.

The following figure files (which live in the directory https://github.com/czbiohub/instapaper/tree/resubmission/figures) have changed / been added (and their associated Jupyter notebooks are in parentheses):

MT:
- insta_figs_mt_fig_2b_inset.png (https://github.com/czbiohub/instapaper/blob/resubmission/figures/MT/fig_2b/fig_2b.ipynb)
- insta_figs_mt_fig_5.png (https://github.com/czbiohub/instapaper/blob/resubmission/figures/MT/vignette_notebooks_and_figs/RCA/MT_Fig_5_sensitivity_lmp_0_1.ipynb)

SI:
- insta_figs_si_fig_1.png (no associated notebook)
- insta_figs_si_fig_4.png (https://github.com/czbiohub/instapaper/blob/resubmission/figures/SI/fig_4/fig_4.ipynb)
- insta_figs_si_fig_6.png (https://github.com/czbiohub/instapaper/blob/resubmission/figures/SI/fig_6/fig_6_plus_signs.ipynb)
- insta_figs_si_fig_10.png (https://github.com/czbiohub/instapaper/blob/resubmission/figures/MT/vignette_notebooks_and_figs/RCA/pipeline_test_RCA.ipynb)
- insta_figs_si_fig_14.png (https://github.com/czbiohub/instapaper/blob/resubmission/figures/MT/vignette_notebooks_and_figs/RCA/SI_Fig_14_error_modes.ipynb)
- contents of insta_figs_si_fig_2_parts (https://github.com/czbiohub/instapaper/blob/resubmission/figures/MT/vignette_notebooks_and_figs/RCA/SI_Fig_14_error_modes.ipynb)

Sometimes I have trouble rendering Jupyter notebooks in github and it's necessary to view it at https://nbviewer.jupyter.org/

Thank you!
Jenny

**Review by kevinyamauchi — COMMENTED** [review]
edit: I meant to approve not comment...sorry!

**Review by kevinyamauchi — APPROVED** [review]
Thanks again, @JennyVoPhamhi ! I think this looks great. I really appreciate having notebooks to reproduce the figures. The last thing is it would be great if you could add a file to the base directory that gives the info required to reproduce your python environment. That way if you or somebody else who needs to use these files in the future doesn't have to worry about issues arising from different versions. I can't remember how you manage your packages, so I've listed a couple of potentially useful threads below. Please feel free to merge after you've done so!

- [anaconda instructions](https://stackoverflow.com/questions/41274007/anaconda-export-environment-file)
- [pip instructions](https://stackoverflow.com/questions/31684375/automatically-create-requirements-txt)

**Comment by JennyVoPhamhi** [comment]
Thank you, @kevinyamauchi! Those links are super helpful. I did `pip3 freeze > requirements.txt` just now and added it to the instapaper repo. I should have thought to do that, since we have that for the instapipeline repo!

I'll merge now!

**Comment by kevinyamauchi** [comment]
🎉

**Pull request merged**
