### PR TITLE
Updated requirements.txt and changed all as_matrix() to to_numpy()

### PR DESCRIPTION
**Pull request by JennyVoPhamhi**
Hi everyone,

To clarify my proposal regarding updated installation instructions for this repo (instapaper): I think it would help users if I indicate in the README for this repo that they should run pip install -r requirements.txt (that is, the file in this repo) and that they should follow the installation instructions in the README for the instapipeline repo. This repo (the instapaper repo) does not have its own setup.py file, so these instructions would help users avoid conclusion.

Do you think this would work?

Thank you!
Jenny

### CODE REVIEW

**Comment by kevinyamauchi** [comment]
Hey @JennyVoPhamhi ! Thank you for this. I think this is really close. I think your suggestion to add instructions on how to set up the environment is a really good one. The current `requirements.txt` file is really strict (i.e., specific versions are specified for each dependency), which is good for reproducibility, but will make it difficult for people to install into their own environments without conflicts. Therefore, I suggest the follow:

1. Determine which are the main dependencies. That is, the dependencies a user would actually install (e.g, `numpy`, `scipy`) as opposed to the ones that are "subdependencies" (e.g., `urllib3`).
2. Add a note to the readme listing the main dependencies. Also give a one line codeblock to install then (e.g., `pip install numpy scipy <rest of dependencies>`)
4. Add a note that a requirements.txt file is included with the exact versions the paper figures were generated with for reproducibility. Include the line you suggested (`pip install -r requirements.txt`) to install the dependencies.


How does this sound?

**Comment by ovynnej** [comment]
Hi @kevinyamauchi ! 

This sounds great to me. Thank you for the detailed guidance! I will do these things and then ask for your feedback.

Thank you!
Jenny

**Comment by ovynnej** [comment]
Hi Kevin,

I have updated the README with the installation instructions as you described. Do you think I hit all the main dependencies?

Detailed requirements.txt: https://github.com/czbiohub/instapaper/blob/dependencies/requirements.txt

What I think are the main dependencies: ipython matplotlib numpy pandas scikit-image scikit-learn scipy starfish

Also, dependabot is asking us to bump urllib3 again to 1.26.4 in requirements.txt. Very recently, on March 26, it wanted us to bump to 1.26.3 (which we did). Should we go ahead and just bump urllib3 every time it asks us to bump it?

Thank you!
Jenny

**Comment by kevinyamauchi** [comment]
> What I think are the main dependencies: ipython matplotlib numpy pandas scikit-image scikit-learn scipy starfish

I think this looks good! can you please confirm by making a fresh environment with the "main dependencies" works?

> Also, dependabot is asking us to bump urllib3 again to 1.26.4 in requirements.txt. Very recently, on March 26, it wanted us to bump to 1.26.3 (which we did). Should we go ahead and just bump urllib3 every time it asks us to bump it?

I would bump it this time in the requirements.txt. In the future, I think we can ignore it because that file is just so people can re-run the notebooks (i.e., the versions should be frozen for reproducibility). Maybe we can rename it to something else, so it doesn't get parsed by the dependabot. Maybe something like `reproduce_paper_environment.txt`?

**Comment by ovynnej** [comment]
Hi Kevin,

Got it. This plan sounds great to me. I will do these things!

Thank you,
Jenny

**Comment by ovynnej** [comment]
Hi Kevin,

Just a quick update:

I renamed requirements.txt to reproduce_paper_environment.txt so it doesn't get parsed by the dependabot. The second part of the most recent commit message is now inaccurate. I will do that after I figure out this issue:

When I created a fresh environment with instapipeline and the main dependencies to confirm that the figure notebooks in instapaper run, I realized I actually have an issue. When I try to do `pip3 install .` in the instapipeline directory to install instapipeline in this fresh new environment, I get the following message about pandas:

```
ERROR: Could not find a version that satisfies the requirement pandas==1.0.1 (from instapipeline)
ERROR: No matching distribution found for pandas==1.0.1
```

However, pandas seems to be working fine. I'm going to see if I can figure out how not to get that pandas installation error message to go away. It might have to do with python versions or it might be an issue with my anaconda installation. I think I have encountered this problem in the past, so I will go through my notes.

Just wanted to update you!

Thank you,
Jenny

**Pull request merged**
